name: Build Files
on:
  push:
    ignore-tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.com
      - run: yarn --frozen-lockfile

      - name: Cache downloads
        uses: actions/cache@v2
        path: downloads
        key: downloads

      - run: make
